Num1 = int(47)
Num2 = int(102)
Sum = Num1 + Num2
Diff = Num2 - Num1
Product = Sum * Diff
print(f"{Num1} + {Num2} = {Sum}")
print(f"{Num2} - {Num1} = {Diff}")
print(f"{Num1} * {Num2} = {Product}")
print(f"( {Num1} + {Num2} ) * ( {Num2} - {Num1} ) = {Product}")