print("Program starting.")
car_brand = input("Insert car brand: ")
car_model = input("Inster car model: ")
print(f"Car brand is \"{car_brand}\" and the modelk is '{car_model}'.")
print("Program ending.")