print("Programming starting.")
print("Estimate how many minutes you spent on programming...")
print("")
A1_T1 = int(input("A1_T1: "))
A1_T2 = int(input("A1_T2: "))
A1_T3 = int(input("A1_T3: "))
A1_T4 = int(input("A1_T4: "))
A1_T5 = int(input("A1_T5: "))
A1_T6 = int(input("A1_T6: "))
A1_T7 = int(input("A1_T7: "))
print("")
sum = A1_T1+A1_T2+A1_T3+A1_T4+A1_T5+A1_T6+A1_T7
print(f"In total you spend {sum} minutes on programming.")
print(f"Average per task was {round((sum/7), 2)} min and same rounder to the nearest integer {round((sum/7))} min.")
print("")
print("Program ending.")